Fixed REMOTE_USER authentication with Python 3
